### ISSUE TITLE
[RFC] Versioned Docs

### ISSUE THREAD

**Issue by pedro-psb** [dynaconf/dynaconf#925]
**Is your feature request related to a problem? Please describe.**
Documentation changes sometimes refer to changes that are still unreleased. Eg, the new `add_converter` feature is not available in `v3.1.12`, but it is [already live](https://www.dynaconf.com/django/#use-django-functions-inside-custom-settings) in the docs.

Also, it should provide more flexibility to change header/links without breaking them (the permalinks should be bound to the version)

**Describe the solution you'd like**
Implement versioned docs: https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/

I'm not sure if this should be done for `v3.1.13` or `v4`.

**Describe alternatives you've considered**
Hold doc merges until a new release is available, maybe using a development branch. Still, old docs are "lost" (not available) and link breaking is a risk.

**Additional context**
These changes could be made together with PR #826 (multi-lingual support), because both should introduce significant structural changes to the docs system.

Here is breaf discussion on this: https://github.com/squidfunk/mkdocs-material/discussions/3646

**Comment by mitches-got-glitches** [comment]
As a user I was caught out by this. Had to check the source and the tags to see what was up. Good to see it down as an issue.

**Comment by pedro-psb** [comment]
[This](https://github.com/dynaconf/dynaconf/commit/807a86ed06e973992a63bd49db8a434abb52a60d) should fix this issue for future releases (the next should happen soon). It adds a rule to publish the docs only on release-tagged commits, so they'll be in sync.

**Comment by rochacbruno** [comment]
We still don't have versioned docs, ideally we would have a separate folder for each tag, but I am ok on keeping only the latest.
